### PR TITLE
Update test2.txt

### PR DESCRIPTION
**Pull request by sibeux**
Co-Authored-By: krahanime <103883153+krahanime@users.noreply.github.com>

### CODE REVIEW

**Comment by cardison** [comment]
can you do buy that in step by step that would be really helpful for me

**Comment by sibeux** [comment]
> 

Sure, lets me explain how get this achievement

**Comment by sibeux** [comment]
@cardison 

1. You should install github for dekstop (because this is the easiest way)
2. Open any repository on your github desktop and clone it to local storage on your computer
3. After that, create a new brach to commit
4. Make a change in the new branch, then you commit by including CO-AUTHOR in the commit message column (you can add me to CO-AUTHOR)
5. Then do a pull request as usual and merge it. And taaadaa you will get the achievement

If you're still confused, don't hesitate to email me so I can respond faster. Good luck👍

**Comment by cardison** [comment]
thanks for helping me to getting this achievement  this tutorial is really helpful  thanks you sooo much and have a amazing day

**Comment by cardison** [comment]
hi im @cardison so i don't know anything about github. i'm a beginner  so
if you can do that including pictures that would be great
if you don't mind. thanks for sending these step this is really helpful but
if you can include this by pictures it would be much easier for git
beginner like me

**Comment by cardison** [comment]
thanks for your kindfull help

**Comment by AnujMutha** [comment]
Hey @sibeux,

**Comment by AnujMutha** [comment]
Thanks for the detailed steps, for me somehow mine steps were'nt working, but now i have the badge, voila !

**Comment by cardison** [comment]
thanks for your kindfull  help have a amazing day 😁

**Pull request merged**
